print ("welcome to madlibs!")
yeet=input()
print ("ready fam?")
yeety=input()
print ("ok give me a noun")
noun1= input()
print ("ok how about a verb")
verb1= input()
print ("now another noun")
noun2= input()
print ("how about a location")
place= input()
print ("let's try an adjective")
adj= input()
print ("another noun")
noun3= input()
print ("one more noun")
noun4= input()
print ("give me a letter of the alphabet")
letter= input()
print ("last one, give me a body part")
bodypart= input()
print ("we're done! ready?")
ya= input()
print ("somebody once told me the " +noun1+ " is gonna " +verb1+ " me. I ain't the sharpest "
       +noun2+ " in the " +place+ ". She was lookin' kinda " +adj+ " with her "
       +noun3+ " and her " +noun4+ " in the shape of a " +letter+ " on her " +bodypart+ ".")

